version: '3.4'

services:
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - catalogdb
  catalogdb:
    container_name: catalogdb
    ports: 
      - "27017:27013"
    volumes:
      - mongo_data:/data/db 