version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile
  catalogdb:
    image: mongo
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Basket.API/Dockerfile
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  basketdb:
    image: redis:alpine
  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Account.Api/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering.Api/Ordering.API/Dockerfile

  ocelotgateawy:
    image: ${DOCKER_REGISTRY-}ocelotgateawy
    build:
      context: .
      dockerfile: Services/OcelotGateawy/Dockerfile

volumes:
  mongo_data:



