version: '3.4'

services:
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDB"
      - "DatabaseSettings__CollectionName=Products"
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - catalogdb
  catalogdb:
    container_name: catalogdb
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
    depends_on:
      - basketdb
  basketdb:
    container_name: basketdb
    ports:
      - "6379:6379"

